# Generated by Django 3.0.3 on 2020-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_index=True, null=True)),
                ('active_power_p', models.FloatField(default=0.0)),
                ('active_power_m', models.FloatField(default=0.0)),
                ('reactive_power_p', models.FloatField(default=0.0)),
                ('reactive_power_m', models.FloatField(default=0.0)),
                ('apparent_power_p', models.FloatField(default=0.0)),
                ('apparent_power_m', models.FloatField(default=0.0)),
                ('power_factor', models.FloatField(default=0.0)),
                ('supply_frequency', models.FloatField(default=0.0)),
                ('active_energy_p', models.FloatField(default=0.0)),
                ('active_energy_m', models.FloatField(default=0.0)),
                ('reactive_energy_p', models.FloatField(default=0.0)),
                ('reactive_energy_m', models.FloatField(default=0.0)),
                ('apparent_energy_p', models.FloatField(default=0.0)),
                ('apparent_energy_m', models.FloatField(default=0.0)),
            ],
        ),
    ]
