# Generated by Django 3.0.6 on 2020-05-10 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestEntity',
        ),
    ]
