# Generated by Django 3.2.3 on 2021-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wetterdaten',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datumzeit', models.DateTimeField(null=True)),
                ('t', models.FloatField()),
                ('p', models.FloatField()),
                ('h', models.FloatField(null=True)),
                ('dir', models.FloatField(null=True)),
                ('v', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['datumzeit'],
            },
        ),
    ]
