# Generated by Django 2.2.6 on 2019-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wetterdaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumzeit', models.DateTimeField(null=True)),
                ('t', models.FloatField()),
                ('p', models.FloatField()),
                ('h', models.FloatField(null=True)),
                ('vbatt', models.FloatField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
            ],
            options={
                'ordering': ['datumzeit'],
            },
        ),
    ]
