# Generated by Django 3.1.2 on 2020-12-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetterdaten', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wetterdaten',
            old_name='vbatt',
            new_name='dir',
        ),
        migrations.RemoveField(
            model_name='wetterdaten',
            name='status',
        ),
        migrations.AddField(
            model_name='wetterdaten',
            name='v',
            field=models.FloatField(null=True),
        ),
    ]
