# Generated by Django 3.2.3 on 2021-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wetterdaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wetterdaten',
            name='datumzeit',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
