from blauen.settings.common import TZ

TIMEZONE = TZ

DAUER_TAG = 'Tag'
DAUER_WOCHE = 'Woche'
DAUER_MONAT = 'Monat'
DAUER_VIERTELJAHR = 'Vierteljahr'
DAUER_HALBES_JAHR = 'halbes Jahr'
DAUER_JAHR = 'Jahr'
DAUER_SELECT = 'Eingabe'

PERIODS = (
    (DAUER_TAG, DAUER_TAG),
    (DAUER_WOCHE, DAUER_WOCHE),
    (DAUER_MONAT, DAUER_MONAT),
    (DAUER_VIERTELJAHR, DAUER_VIERTELJAHR),
    (DAUER_HALBES_JAHR, DAUER_HALBES_JAHR),
    (DAUER_JAHR, DAUER_JAHR),
    (DAUER_SELECT, DAUER_SELECT),
)

ZEIT_INTERVALL = [120, 300, 1200, 3600, 7200, 14400]
